"""Comparison pages: /vs/{competitor}.

Moved verbatim out of cloud/api.py; rendered by cloud/site.py."""

VS_PAGES = {
    "cognee": {
        "slug": "cognee",
        "name": "Cognee",
        "tagline": "Cognee builds a knowledge graph. Mengram learns your workflows.",
        "description": "Cognee is a strong open-source knowledge-graph memory engine — it turns your data into a graph of entities and relationships and runs the whole memory layer on a single Postgres. Mengram overlaps on facts and graph, but adds what Cognee doesn't: procedural memory (workflows that evolve from failures), a cognitive profile, native multilingual retrieval, and Claude Code hooks.",
        "their_good": [
            "Knowledge-graph-first retrieval — answers relational/causal questions flat RAG can't",
            "Runs graph + vectors + sessions on a single Postgres (simple ops)",
            "Ontology-grounded extraction (ECL pipeline)",
            "Large community (29k+ stars), Apache 2.0, MCP + LangGraph integrations",
        ],
        "their_missing": [
            "No procedural memory — workflows with versions that evolve from successes and failures",
            "No distinct episodic layer (events/decisions/outcomes as a first-class type)",
            "No cognitive profile — a ready-to-use system prompt distilled from everything it knows about you",
            "No native multilingual retrieval",
            "MCP-only for Claude Code — no auto-save/auto-recall hooks, so capture isn't automatic",
        ],
        "has_semantic": "&#x2705;",
        "has_episodic": "&#x274C;",
        "has_multiuser": "&#x2705;",
        "has_graph": "&#x2705;",
        "has_mcp": "&#x2705;",
        "has_selfhost": "&#x2705;",
        "their_price": "Free (OSS), usage-priced cloud",
        "best_for_them": "Building a queryable knowledge graph over documents and data where relational/causal retrieval is the priority. Cognee's graph is genuinely strong for that.",
        "best_for_us": "Memory that learns how you work: procedural workflows with success/failure evolution, a cognitive profile, one memory shared across Claude Code (hooks), Cursor, and Codex, and multilingual retrieval in 23 languages.",
        "website": "https://github.com/topoteretes/cognee",
        "seo_title": "Mengram vs Cognee — Knowledge Graph vs Workflow Memory (2026)",
        "seo_description": "Cognee builds a knowledge graph over your data. Mengram adds procedural memory (workflows that evolve from failures), a cognitive profile, multilingual retrieval, and Claude Code hooks. Honest comparison.",
        "seo_keywords": "cognee alternative, Mengram vs Cognee, cognee vs mem0, AI memory knowledge graph, procedural memory, claude code memory",
    },
    "hindsight": {
        "slug": "hindsight",
        "name": "Hindsight",
        "tagline": "Hindsight nails retrieval. Mengram adds workflow memory and a profile.",
        "description": "Hindsight (by Vectorize) is a strong open-source agent-memory system — it leads the LongMemEval benchmark with excellent hybrid retrieval and a retain/recall/reflect loop. Mengram overlaps on facts and retrieval, and differentiates on procedural memory (workflows that evolve from failures), a cognitive profile, native multilingual retrieval, and Claude Code hooks rather than MCP-only.",
        "their_good": [
            "State-of-the-art retrieval — 91.4% on LongMemEval (first to break 90%)",
            "Hybrid recall: semantic + BM25 + entity-graph + temporal, cross-encoder rerank",
            "retain/recall/reflect with auto-updating mental models",
            "MIT-licensed, fully self-hostable (Docker or embedded), MCP-based",
        ],
        "their_missing": [
            "No procedural memory — versioned workflows that evolve from failures (recording the violated assumption + a precondition)",
            "No cognitive profile — a ready-to-use system prompt generated from all memory",
            "No native multilingual retrieval",
            "MCP-based Claude Code integration — Mengram also ships deterministic auto-save/auto-recall hooks + a capture-policy privacy boundary",
        ],
        "has_semantic": "&#x2705;",
        "has_episodic": "&#x2705;",
        "has_multiuser": "&#x2705;",
        "has_graph": "&#x2705;",
        "has_mcp": "&#x2705;",
        "has_selfhost": "&#x2705;",
        "their_price": "Free (OSS, MIT), managed cloud available",
        "best_for_them": "Maximum recall accuracy on long-horizon fact retrieval — if benchmark-topping semantic/temporal recall is the goal, Hindsight is excellent.",
        "best_for_us": "When how-you-work matters as much as what-you-said: procedural memory with failure-driven evolution, a cognitive profile, deterministic Claude Code hooks, a server-side capture boundary (deny by category/keyword), and multilingual retrieval.",
        "website": "https://hindsight.vectorize.io",
        "seo_title": "Mengram vs Hindsight — Retrieval vs Workflow Memory (2026)",
        "seo_description": "Hindsight leads LongMemEval with excellent retrieval. Mengram adds procedural memory (workflows that evolve from failures), a cognitive profile, Claude Code hooks, and a capture-policy privacy boundary. Honest comparison.",
        "seo_keywords": "hindsight alternative, Mengram vs Hindsight, hindsight vectorize, agent memory, procedural memory, claude code memory, LongMemEval",
    },
    "mem0": {
        "slug": "mem0",
        "name": "Mem0",
        "tagline": "Both store memories. Only Mengram learns workflows.",
        "description": "Mem0 is a popular fact-storage tool with 25K+ GitHub stars. Mengram adds episodic memory, procedural memory that evolves from failures, and Cognitive Profile.",
        "their_good": [
            "25K+ GitHub stars — largest community",
            "Well-funded ($24M, YC S24)",
            "Solid fact retrieval (graph + vector + KV)",
            "Python &amp; JS SDKs with good docs",
        ],
        "their_missing": [
            "No episodic memory (events, decisions)",
            "No procedural memory (workflows)",
            "No self-improving workflows",
            "No Cognitive Profile",
            "English-biased embeddings (OpenAI) — weaker on non-English content",
            "No unified search across memory types",
            "$19–249/mo paid tiers",
        ],
        "has_semantic": "&#x2705;",
        "has_episodic": "&#x274C;",
        "has_multiuser": "&#x2705;",
        "has_graph": "&#x2705;",
        "has_mcp": "&#x2705;",
        "has_selfhost": "&#x2705;",
        "their_price": "$19–249/mo",
        "best_for_them": "Reliable fact storage with the largest community. Great if you only need to remember user preferences and personal details.",
        "best_for_us": "Agents that learn from experience — remember facts AND events AND workflows. Cloud API with 3 memory types, Cognitive Profile, native multilingual support in 23 languages (Cohere multilingual-v3), and MCP.",
        "website": "https://mem0.ai",
        "seo_title": "Mengram vs Mem0 — AI Memory Comparison (2026)",
        "seo_description": "Compare Mengram and Mem0 for AI agent memory. Mengram adds episodic + procedural memory, Cognitive Profile, and native multilingual support in 23 languages. Plans from $5/mo.",
        "seo_keywords": "Mem0 alternative, Mengram vs Mem0, AI memory comparison, mem0ai alternative, multilingual AI memory, best AI memory tool",
    },
    "zep": {
        "slug": "zep",
        "name": "Zep",
        "tagline": "Zep tracks time. Mengram learns from experience.",
        "description": "Zep is an enterprise AI memory tool with temporal knowledge graph and SOC2/HIPAA compliance. Mengram offers 3 memory types, procedural learning, and a cloud API.",
        "their_good": [
            "Temporal knowledge graph — tracks how facts change over time",
            "SOC2 and HIPAA compliance",
            "Sub-200ms latency targets",
            "Python, TypeScript, and Go SDKs",
        ],
        "their_missing": [
            "Cloud-only (community edition deprecated)",
            "Enterprise pricing only — no affordable plans",
            "No episodic memory",
            "No procedural memory",
            "No self-improving workflows",
            "No Cognitive Profile",
            "English-only retrieval — no native multilingual embeddings",
        ],
        "has_semantic": "&#x2705;",
        "has_episodic": "&#x274C;",
        "has_multiuser": "&#x2705;",
        "has_graph": "&#x2705;",
        "has_mcp": "&#x274C;",
        "has_selfhost": "&#x274C;",
        "their_price": "Enterprise",
        "best_for_them": "Enterprise apps in regulated industries (healthcare, finance) where SOC2/HIPAA and temporal reasoning are requirements.",
        "best_for_us": "Agents that learn and improve over time. 3 memory types, cloud API, self-hostable, native multilingual support in 23 languages, MCP + LangChain + CrewAI integrations.",
        "website": "https://www.getzep.com",
        "seo_title": "Mengram vs Zep — AI Memory Comparison (2026)",
        "seo_description": "Compare Mengram and Zep for AI agent memory. Mengram offers 3 memory types, procedural learning, and native multilingual support in 23 languages. Open-source, plans from $5/mo vs Zep enterprise pricing.",
        "seo_keywords": "Zep alternative, zep pricing, zep ai memory pricing 2026, zep memory pricing, zep alternatives, Mengram vs Zep, AI memory comparison, getzep alternative, multilingual AI memory, AI memory API",
    },
    "letta": {
        "slug": "letta",
        "name": "Letta",
        "tagline": "Letta lets agents self-curate. Mengram gives them 3 memory types.",
        "description": "Letta (formerly MemGPT) pioneered agent-controlled memory from UC Berkeley research. Mengram takes a different approach with 3 structured memory types and procedural learning.",
        "their_good": [
            "Novel agent-controlled memory architecture",
            "UC Berkeley research-backed (MemGPT paper)",
            "Free and self-hostable",
            "Great for long-running conversations",
        ],
        "their_missing": [
            "No procedural memory",
            "Only partial episodic memory (conversation archival)",
            "No self-improving workflows",
            "No Cognitive Profile",
            "English-only retrieval — no native multilingual support",
            "Agent memory management adds unpredictability",
            "Limited managed hosting options",
        ],
        "has_semantic": "&#x2705;",
        "has_episodic": "Partial",
        "has_multiuser": "&#x274C;",
        "has_graph": "&#x274C;",
        "has_mcp": "&#x2705;",
        "has_selfhost": "&#x2705;",
        "their_price": "Free (self-host)",
        "best_for_them": "Long-running conversational agents where the agent should organically manage its own context and memory.",
        "best_for_us": "Structured memory with 3 types that the developer controls. Procedures evolve from failures. Native multilingual support in 23 languages. Cloud API + MCP + framework integrations.",
        "website": "https://www.letta.com",
        "seo_title": "Mengram vs Letta (MemGPT) — AI Memory Comparison (2026)",
        "seo_description": "Compare Mengram and Letta (MemGPT) for AI agent memory. Mengram offers semantic + episodic + procedural memory, self-improving workflows, and native multilingual support in 23 languages. Plans from $5/mo.",
        "seo_keywords": "Letta alternative, MemGPT alternative, letta formerly memgpt, letta vs memgpt 2026, letta successor to memgpt, letta vs memgpt differences, Mengram vs Letta, AI memory comparison, multilingual AI memory, best AI memory tool 2026",
    },
    "langmem": {
        "slug": "langmem",
        "name": "LangMem",
        "tagline": "LangMem extends LangGraph. Mengram works with everything.",
        "description": "LangMem is LangChain's memory module for LangGraph agents. Mengram is a standalone memory API that works with any framework — LangChain, CrewAI, OpenAI, or direct API calls.",
        "their_good": [
            "Native LangGraph integration — first-class LangChain support",
            "Thread-scoped and cross-thread memory",
            "Backed by LangChain team — strong ecosystem alignment",
            "Memory formed via background processing",
        ],
        "their_missing": [
            "Tightly coupled to LangGraph — harder to use outside LangChain",
            "No episodic memory (events, decisions)",
            "No procedural memory (workflows)",
            "No Cognitive Profile",
            "No standalone MCP server",
            "No knowledge graph visualization",
            "English-only retrieval — no native multilingual embeddings",
        ],
        "has_semantic": "&#x2705;",
        "has_episodic": "&#x274C;",
        "has_multiuser": "&#x2705;",
        "has_graph": "&#x274C;",
        "has_mcp": "&#x274C;",
        "has_selfhost": "&#x2705;",
        "their_price": "Via LangSmith plans",
        "best_for_them": "Teams already using LangGraph and LangSmith who want memory deeply integrated into their LangChain workflow.",
        "best_for_us": "Framework-agnostic memory with 3 types. Works with any LLM, any framework, any client. Native multilingual retrieval in 23 languages. Cloud API + MCP + Cognitive Profile.",
        "website": "https://langchain-ai.github.io/long-term-memory/",
        "seo_title": "Mengram vs LangMem — AI Memory Comparison (2026)",
        "seo_description": "Compare Mengram and LangMem for AI agent memory. Mengram offers 3 memory types, Cognitive Profile, native multilingual support in 23 languages, and framework-agnostic API. Works beyond LangChain.",
        "seo_keywords": "LangMem alternative, Mengram vs LangMem, LangChain memory alternative, AI memory comparison, multilingual AI memory, LangGraph memory",
    },
    "supermemory": {
        "slug": "supermemory",
        "name": "Supermemory",
        "tagline": "Supermemory bookmarks the web. Mengram remembers conversations.",
        "description": "Supermemory is a personal knowledge manager that saves and searches bookmarks, tweets, and web content. Mengram is an AI memory API that extracts and stores memories from conversations.",
        "their_good": [
            "Great browser extension for saving web content",
            "ChatGPT-style interface for querying saved content",
            "Good for personal knowledge management",
            "Open source and self-hostable",
        ],
        "their_missing": [
            "Not designed for AI agent memory — it's a bookmark tool",
            "No conversation memory extraction",
            "No episodic memory",
            "No procedural memory",
            "No Cognitive Profile",
            "No multi-user isolation for agent use cases",
            "No MCP server",
            "No native multilingual retrieval",
        ],
        "has_semantic": "Partial",
        "has_episodic": "&#x274C;",
        "has_multiuser": "&#x274C;",
        "has_graph": "&#x274C;",
        "has_mcp": "&#x274C;",
        "has_selfhost": "&#x2705;",
        "their_price": "Free (self-host)",
        "best_for_them": "Personal knowledge management — saving bookmarks, tweets, and web articles for later retrieval and search.",
        "best_for_us": "AI agent memory that learns from conversations. 3 memory types, Cognitive Profile, MCP server, native multilingual support in 23 languages, and multi-user isolation for production apps.",
        "website": "https://supermemory.ai",
        "seo_title": "Mengram vs Supermemory — AI Memory Comparison (2026)",
        "seo_description": "Compare Mengram and Supermemory. Supermemory is a bookmark manager. Mengram is an AI memory API with semantic, episodic, procedural memory and native multilingual support in 23 languages.",
        "seo_keywords": "Supermemory alternative, Mengram vs Supermemory, AI memory comparison, multilingual AI memory, best AI memory 2026, Supermemory vs Mengram",
    },
    "claude-mem": {
        "slug": "claude-mem",
        "name": "claude-mem",
        "tagline": "claude-mem remembers your sessions. Mengram learns your workflows.",
        "description": "claude-mem is an excellent session-memory tool: it captures what happened in your coding sessions, summarizes it, and re-injects relevant context later. Mengram solves a different problem on top of that — procedural memory: it learns HOW you work (deploy, debug, ship) as versioned workflows that evolve every time you succeed or fail, plus a structured entity graph and a cognitive profile.",
        "their_good": [
            "Session-observation capture with AI summarization and context re-injection",
            "Hybrid search (SQLite FTS + Chroma vectors)",
            "MCP tools for memory search and timeline",
            "Multi-tool installers (Claude Code, OpenCode and others)",
            "Local-first with optional cloud backup, Apache 2.0, huge community",
        ],
        "their_missing": [
            "No procedural memory — workflows with versions that evolve from successes and failures",
            "No cognitive profile — a ready-to-use system prompt distilled from everything it knows about you",
            "Observation/summary model rather than a structured entity graph (facts, relations, importance, temporal decay)",
            "No multi-user API — built as a personal tool, not a memory backend you can ship inside your own product",
            "No LangChain / CrewAI / voice-agent integrations",
        ],
        "has_semantic": "&#x2705;",
        "has_episodic": "&#x2705;",
        "has_multiuser": "&#x274C;",
        "has_graph": "&#x274C;",
        "has_mcp": "&#x2705;",
        "has_selfhost": "&#x2705;",
        "their_price": "Free (OSS), cloud backup via cmem.ai",
        "best_for_them": "Remembering what happened across Claude Code sessions — capture, summaries, and context re-injection. If session persistence is your whole problem, claude-mem solves it well.",
        "best_for_us": "Memory that learns how you work: procedural workflows with success/failure evolution, a structured knowledge graph, cognitive profile, multi-user API for shipping memory inside your own product, and one memory shared across Claude Code, Cursor, Codex, ChatGPT, LangChain, and CrewAI — in 23 languages.",
        "website": "https://github.com/thedotmack/claude-mem",
        "seo_title": "Mengram vs claude-mem — Session Memory vs Workflow Memory (2026)",
        "seo_description": "claude-mem remembers what happened in your sessions. Mengram learns how you work — procedural workflows that evolve from successes and failures, entity graph, cognitive profile, multi-user API. Honest comparison.",
        "seo_keywords": "claude-mem alternative, Mengram vs claude-mem, Claude Code memory, procedural memory AI agent, AI agent learns workflows, Claude Code persistent memory, claude code workflow memory",
    },
}
